[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 0
via_ir = true
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts",
    "@chainlink=lib/chainlink",
]
